# Generated by Django 3.0 on 2021-08-18 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210817_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, editable=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Huella dactilar',
                'verbose_name_plural': 'Huellas dactilares',
                'db_table': 'fingerprint',
                'unique_together': {('employee',)},
            },
        ),
    ]
