# Generated by Django 3.0 on 2021-08-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
