# Generated by Django 3.0 on 2021-08-18 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_fingerprint'),
        ('registration', '0002_auto_20210817_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='fingerprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Fingerprint', verbose_name='Huella dactilar'),
        ),
    ]
