# Generated by Django 3.0 on 2021-08-18 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_register_fingerprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='employee',
        ),
    ]
